### ISSUE TITLE
Update links for phonebook and directory

### ISSUE THREAD

**Issue by danahertzberg** [az-marketing/slate-template#43]
Match https://github.com/az-digital/az_quickstart/issues/2786

## Motivation
When the Directory is launched on QS2, the phonebook will also launch separately. This determines a need for updated links in the global footer.

## Proposed Resolution
![image](https://github.com/az-digital/az_quickstart/assets/59745109/3aa9e95b-2d25-4cf6-b64f-a57151032bf9)

### Describe the solution you'd like
1. Change `A-Z Index` link to `Directory` with URL https://directory.arizona.edu
2. Change `Phonebook` URL to https://phonebook.arizona.edu

## Additional context
The externally referenced footer is not updated with changes like these. We need to consider this in the solution as well.
```
<html>
  <body>
    <az-footer>
    <script src="https://cdn.digital.arizona.edu/lib/temp-web-components/1.0.15/az-footer.js"></script>
  </body>
</html>
```

**Comment by danahertzberg** [comment]
Looks like this change was made on main by @Krystation already. I can't see it on https://www.arizona.edu/admissions. So not sure where this stands..

**Comment by Krystation** [comment]
Yo! I just now made that change. I'm updated admission to the new release rn. Should be up in a bit :)
